### ISSUE TITLE
GraphQL /Items endpoint checkAccess doesn't do anything

### ISSUE THREAD

**Issue by willisplummer** [collectiveaccess/providence#1713]
I'm on version 2.0.5a trying to use `checkAccess` to limit related objects to only publicly accessible, but I'm getting back a mix of data that is `internal_only` and `public_access`

I've confirmed that `public_access` has Item value 1 and `internal_only` has value 0.

Here is an example query:
```gql
query GetArtwork($id: Int!) {
  getRelationships(
    table: "ca_collections"
    id: $id
    target: "ca_objects"
    bundles: ["ca_objects.access"]
    checkAccess: [1]
    start: 0
    limit: 5
  ) {
    id
    table
    idno
    relationships {
      id
      table
      relationship_typename
      relationship_typecode
      bundles {
        name
        code
        dataType
        values {
          id
          value_id
          locale
          value
          subvalues {
            id
            code
            value
            dataType
          }
        }
      }
    }
  }
}
```
Here are some of the results showing both access types:
```
        {
          "id": 192,
          "table": "ca_objects_x_collections",
          "relationship_typename": "documentation material",
          "relationship_typecode": "documentation_material",
          "bundles": [
            {
              "name": "Access",
              "code": "ca_objects.access",
              "dataType": null,
              "values": [
                {
                  "id": 0,
                  "value_id": null,
                  "locale": "en_US",
                  "value": "public_access",
                  "subvalues": [
                    {
                      "id": null,
                      "code": "0",
                      "value": "public_access",
                      "dataType": null
                    }
                  ]
                }
              ]
            }
          ]
        },
        {
          "id": 194,
          "table": "ca_objects_x_collections",
          "relationship_typename": "production material",
          "relationship_typecode": "production_material",
          "bundles": [
            {
              "name": "Access",
              "code": "ca_objects.access",
              "dataType": null,
              "values": [
                {
                  "id": 0,
                  "value_id": null,
                  "locale": "en_US",
                  "value": "internal_only",
                  "subvalues": [
                    {
                      "id": null,
                      "code": "0",
                      "value": "internal_only",
                      "dataType": null
                    }
                  ]
                }
              ]
            }
          ]
        },
```

**Comment by willisplummer** [comment]
It looks like the checkAccess argument is read here but not actually used anywhere? https://github.com/collectiveaccess/providence/blob/master/app/service/controllers/ItemController.php#L277

**Comment by collectiveaccess** [comment]
Yeah. It looks like it got disconnected in a refactor a while back. I just pushed a fix. Please. give it a try?

**Comment by willisplummer** [comment]
Thanks for the quick response! Which branch did you push to?

**Comment by collectiveaccess** [comment]
`dev/php2.0`. Link to the commit is in this thread, above.

**Comment by willisplummer** [comment]
That didn't fix it - I'm still getting a mix of internal and public results

**Comment by willisplummer** [comment]
It seems like [here](https://github.com/collectiveaccess/providence/blob/dev/2.0/app/service/controllers/ItemController.php#L424-L446), checkAccess is not set on $t and based on the schema it should probably be passed to `processTarget` as an option instead of as part of $t? Otherwise, you also need to rework the way the targets array is constructed to go in and apply `checkAccess` as a value to each object in the array.
